### ISSUE TITLE
Dodati dio s plugin licencama

### ISSUE THREAD

**Issue by iruzevic** [infinum/wordpress-handbook#100]
Uglavnom pravilo je:

1. Projek kod nas na održavanju 

- Mi kupimo licencu ili već imamo svoju licencu
- Dokle mi supportamo / maintenance ta licenca vrijedi
- Ako klijent odluči otici od nas on ne nosi licencu sa sobom
- Svi pluginovi su po principu plati da možeš updejtati.
- Ako odu moraju kupiti dalje svoju licencu

2. Projekt je po principu ključ u ruke (Mi ne radimo maintenance i nemamo više ništa snjim nakon produkcije)
- Klijent kupuje svoje licence odmah

---------
Treba nadodati da lead dev na projektu obavezno mora obavijestiti PM-a o bilo kakvim placenim pluginovim ukoliko ih korisiti na projektu neovisno o tome imamo li mi svoju licencu ili ne. PM to mora komunicirati klijentu. 

Nadodati ako još treba nešto.

**Comment by dingo-d** [comment]
To sam napravio na private dijelu jer je vise vezano uz interno hendlanje projekta.

https://github.com/infinum/wordpress-handbook-private/pull/7

**Comment by dingo-d** [comment]
PR merged
