### ISSUE TITLE
How to add fonts

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/wordpress-handbook#105]
A simple guide on the standard process of adding fonts with the new boilerplate setup.

**Comment by dingo-d** [comment]
This is added in the docs IIRC, and is also a good candidate for a small how-to article.

**Comment by gabriel-glo** [comment]
Yes there is a chapter for adding fonts. https://infinum.github.io/eightshift-docs/docs/basics/fonts It could be a bit expanded in the future, but I think this should be enough for now.
