### ISSUE TITLE
Exclude languages folder from gitignore

### ISSUE THREAD

**Issue by mate3** [infinum/wordpress-handbook#106]
After facing problem with production site where default language doesn't work well I realised that I was missing WordPress hr language pack. After installing language pack everything worked well.
It was easy fix but we spent too much time to find this issue.
In future we need to exclude wp-content/languages folder in gitignore before somebody else encounter  this error.

**Comment by dingo-d** [comment]
This sounds like an edge case, especially with the new deployment process, this should never happen 🤷🏼‍♂️
