### ISSUE TITLE
[Chapter] Laravel Valet Mailhog configuration

### ISSUE THREAD

**Issue by goranalkovic-infinum** [infinum/wordpress-handbook#150]
**Name of the chapter/subchapter**
(Development environment/Laravel Valet setup/) _MailHog setup_

**Short description about what should be in the chapter**
The chapter should shortly explain what MailHog (https://github.com/mailhog/MailHog) is and why we should use it.

Then the install process would be explained:
1. Installing MailHog with Homebrew
2. Adding the env. variables through `.valet-env.php` (inside one of the project folders)
3. Adding the .ini config file
4. Checking if it works

Useful snippets:
`<project-root>/.valet-env.php`
```php
<?php

return [
	'*' => [
		'MAIL_DRIVER' => 'smtp',
		'MAIL_HOST' => '127.0.0.1',
		'MAIL_PORT' => '1025',
		'MAIL_USERNAME' => 'null',
		'MAIL_PASSWORD' => 'null',
		'MAIL_ENCRYPTION' => 'null',
	],
];
```
---

`/opt/homebrew/etc/php/7.4/conf.d/smtp-mailhog.ini`
```
sendmail_path = /opt/homebrew/opt/mailhog/bin/MailHog sendmail test@test
```

**Comment by dingo-d** [comment]
This no longer works (to be honest not quite sure how this ever worked 🤷🏼‍♂️ ).

The `.valet-env.php` will expose the above-mentioned variables in the `$_SERVER` array, but those won't do anything by themselves.

In order for Mailhog to work, the safest bet is just to use [this plugin](https://wordpress.org/plugins/wp-mailhog-smtp/), which just does the following:

```php
add_action( 'phpmailer_init', function( $phpmailer ) {
  $phpmailer->Host     = '127.0.0.1';
  $phpmailer->Port     = 1025;
  $phpmailer->SMTPAuth = false;
  $phpmailer->isSMTP();
} );
```

Super simple but works.
