### ISSUE TITLE
Add Disaster control steps

### ISSUE THREAD

**Issue by iruzevic** [infinum/wordpress-handbook#96]
Add a chapter for Disaster control steps.
Here is a inspiration that Denis wrote on Tarisio project.

1. Check logs
2. Disable plugins one by one and check if the issue persists
3. Change the theme to the default one (if possible using WP-CLI)
4. Flush cache and clear transients
5. Reset permalink settings
6. If all this fails revert the production code to an earlier stable release

**Comment by dingo-d** [comment]
Added as a part of the private handbook part
