### ISSUE TITLE
PHP Coding standards inline statements

### ISSUE THREAD

**Issue by dom-patrick** [infinum/wordpress-handbook#98]
The first example looks kinda confusing, like the `yes` and `no` statements are the same.

https://handbook.infinum.co/books/wordpress/coding-standards/php-coding-standards#inline-statements
<img width="819" alt="Screenshot 2019-11-12 at 11 47 35" src="https://user-images.githubusercontent.com/54271730/68665883-2894a780-0543-11ea-9c11-91858035ad73.png">

**Comment by dingo-d** [comment]
Indeed it's a bug, it should be 

```php
// Yes:
<?php echo esc_html( $x ); ?>

// No:
<?php
  echo esc_html( $x );
?>
```

Will fix this asap 🙂 👍

**Comment by dingo-d** [comment]
This has been fixed
