### ISSUE TITLE
Broken link in Guttenberg chapter

### ISSUE THREAD

**Issue by ghost** [infinum/wordpress-handbook#99]
I found a broken 404 link on the Documentation section.
Link: https://handbook.infinum.co/books/wordpress/gutenberg/general

**Comment by iruzevic** [comment]
Go and fix it :

1. change https://github.com/infinum/eightshift-boilerplate-internal to https://github.com/infinum/eightshift-boilerplate

2. Remove - https://github.com/infinum/eightshift-blocks

**Comment by dingo-d** [comment]
Fixed this. Thanks!
